/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface ExampleSwapToPriceInterface extends utils.Interface {
  functions: {
    "factory()": FunctionFragment;
    "router()": FunctionFragment;
    "swapToPrice(address,address,uint256,uint256,uint256,uint256,address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "factory" | "router" | "swapToPrice"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(functionFragment: "router", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "swapToPrice",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "router", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapToPrice",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ExampleSwapToPrice extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ExampleSwapToPriceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    factory(overrides?: CallOverrides): Promise<[string]>;

    router(overrides?: CallOverrides): Promise<[string]>;

    swapToPrice(
      tokenA: PromiseOrValue<string>,
      tokenB: PromiseOrValue<string>,
      truePriceTokenA: PromiseOrValue<BigNumberish>,
      truePriceTokenB: PromiseOrValue<BigNumberish>,
      maxSpendTokenA: PromiseOrValue<BigNumberish>,
      maxSpendTokenB: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  factory(overrides?: CallOverrides): Promise<string>;

  router(overrides?: CallOverrides): Promise<string>;

  swapToPrice(
    tokenA: PromiseOrValue<string>,
    tokenB: PromiseOrValue<string>,
    truePriceTokenA: PromiseOrValue<BigNumberish>,
    truePriceTokenB: PromiseOrValue<BigNumberish>,
    maxSpendTokenA: PromiseOrValue<BigNumberish>,
    maxSpendTokenB: PromiseOrValue<BigNumberish>,
    to: PromiseOrValue<string>,
    deadline: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    factory(overrides?: CallOverrides): Promise<string>;

    router(overrides?: CallOverrides): Promise<string>;

    swapToPrice(
      tokenA: PromiseOrValue<string>,
      tokenB: PromiseOrValue<string>,
      truePriceTokenA: PromiseOrValue<BigNumberish>,
      truePriceTokenB: PromiseOrValue<BigNumberish>,
      maxSpendTokenA: PromiseOrValue<BigNumberish>,
      maxSpendTokenB: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    factory(overrides?: CallOverrides): Promise<BigNumber>;

    router(overrides?: CallOverrides): Promise<BigNumber>;

    swapToPrice(
      tokenA: PromiseOrValue<string>,
      tokenB: PromiseOrValue<string>,
      truePriceTokenA: PromiseOrValue<BigNumberish>,
      truePriceTokenB: PromiseOrValue<BigNumberish>,
      maxSpendTokenA: PromiseOrValue<BigNumberish>,
      maxSpendTokenB: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    router(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    swapToPrice(
      tokenA: PromiseOrValue<string>,
      tokenB: PromiseOrValue<string>,
      truePriceTokenA: PromiseOrValue<BigNumberish>,
      truePriceTokenB: PromiseOrValue<BigNumberish>,
      maxSpendTokenA: PromiseOrValue<BigNumberish>,
      maxSpendTokenB: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
